import = ['~/.config/alacritty/catppuccin-macchiato.toml']

live_config_reload=true

[shell]
program = "zsh"
args = ["-l", "-c", "zellij attach --index 0 || zellij"]

[window]
decorations = "Full"
dynamic_title = false
padding = { y = 10, x = 4 }

[font]
normal = { family = "FiraCode Nerd Font Mono"}
size = 14

