#!/usr/bin/env bash

set -e

DOTBOT_DIR="dotbot"
DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"
git -C "${DOTBOT_DIR}" submodule sync --quiet --recursive
git submodule update --init --recursive "${DOTBOT_DIR}"

run_dotbot() {
  "${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "$1" "${@:2}"
}

run_dotbot shared.conf.yaml "${@}"

if [[ "$OSTYPE" == "darwin"* ]]; then
  run_dotbot mac.conf.yaml "${@}"
else
  run_dotbot linux.conf.yaml "${@}"
fi
