buttons:
  - label: "Logout"
    action: "hyprctl dispatch exit"
  - label: "Reboot"
    action: "hyprshutdown --vt 2 -t 'Restarting...' --post-cmd 'reboot'"
  - label: "Shutdown"
    action:
      "hyprshutdown --vt 2 -t 'Shutting down...' --post-cmd 'shutdown -P 0'"
  - label: "Lock"
    action: "hyprlock"
