"$schema" = "https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json"

final_space = true
version = 2

[[blocks]]
type = "prompt"
alignment = "left"

  [[blocks.segments]]
  type = "path"
  style = "plain"
  template = "{{ .Path }} "
  foreground = "#bd93f9"

    [blocks.segments.properties]
    home_icon = "~"
    style = "agnoster_full"

[[blocks]]
type = "prompt"
alignment = "left"
newline = true

  [[blocks.segments]]
  type="text"
  style="plain"
  foreground="#ff79c6"
  template="❯"

[[blocks]]
type="rprompt"
alignment="right"

  [[blocks.segments]]
  type="git"
  style="powerline"
  background="#ffb86c"
  foreground="#282a36"
  powerline_symbol=""

    [blocks.segments.properties]
    branch_icon = ""
    fetch_stash_count = true
    fetch_status = true
    fetch_upstream_icon = true
    template = " ➜ ({{ .UpstreamIcon }}{{ .HEAD }}{{ if gt .StashCount 0 }}  {{ .StashCount }}{{ end }}) "

[transient_prompt]
background = "transparent"
foreground = "#ffffff"
template = "❯ "
