preload = /home/joren/Pictures/wallpapers/orange-landscape.png

wallpaper {
    monitor = DP-1
    path = /home/joren/Pictures/wallpapers/orange-landscape.png
    fit_mode = cover
}

wallpaper {
    monitor = DP-2
    path = /home/joren/Pictures/wallpapers/orange-landscape.png
    fit_mode = cover
}

splash = false
